import type { Product, Category, Customer, Employee, Supplier, MeasurementService, InstallationService } from "./types"

export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Papel de Parede",
    slug: "papel-de-parede",
    description: "Papéis de parede para todos os ambientes e estilos",
    image: "/images/category-papel-parede.png",
    specifications: ["Largura do rolo", "Comprimento", "Padrão", "Textura", "Lavável", "Removível"],
    subcategories: [
      {
        id: "1-1",
        name: "Papel de Parede Vinílico",
        slug: "vinilico",
        description: "Resistente à umidade, ideal para cozinhas e banheiros",
        image: "/images/papel-vinilico.png",
        parentId: "1",
      },
      {
        id: "1-2",
        name: "Papel de Parede TNT",
        slug: "tnt",
        description: "Fácil aplicação e remoção, perfeito para iniciantes",
        image: "/images/papel-tnt.png",
        parentId: "1",
      },
      {
        id: "1-3",
        name: "Papel de Parede 3D",
        slug: "3d",
        description: "Efeitos tridimensionais para ambientes modernos",
        image: "/images/papel-3d.png",
        parentId: "1",
      },
      {
        id: "1-4",
        name: "Papel de Parede Infantil",
        slug: "infantil",
        description: "Designs lúdicos e educativos para quartos infantis",
        image: "/images/papel-infantil.png",
        parentId: "1",
      },
    ],
  },
  {
    id: "2",
    name: "Cortinas",
    slug: "cortinas",
    description: "Cortinas sob medida para todos os ambientes",
    image: "/images/category-cortinas.png",
    specifications: ["Tecido", "Opacidade", "Largura", "Altura", "Tipo de instalação"],
    subcategories: [
      {
        id: "2-1",
        name: "Cortinas Blackout",
        slug: "blackout",
        description: "Bloqueio total da luz para quartos e home theater",
        image: "/images/cortina-blackout.png",
        parentId: "2",
      },
      {
        id: "2-2",
        name: "Cortinas Translúcidas",
        slug: "translucidas",
        description: "Filtragem suave da luz natural",
        image: "/images/cortina-translucida.png",
        parentId: "2",
      },
      {
        id: "2-3",
        name: "Cortinas Rolô",
        slug: "rolo",
        description: "Praticidade e modernidade para qualquer ambiente",
        image: "/images/cortina-rolo.png",
        parentId: "2",
      },
      {
        id: "2-4",
        name: "Cortinas Romanas",
        slug: "romanas",
        description: "Elegância clássica com dobras horizontais",
        image: "/images/cortina-romana.png",
        parentId: "2",
      },
    ],
  },
  {
    id: "3",
    name: "Decoração",
    slug: "decoracao",
    description: "Objetos decorativos para personalizar seus ambientes",
    image: "/images/category-decoracao.png",
    specifications: ["Material", "Dimensões", "Peso", "Estilo", "Ambiente"],
    subcategories: [
      {
        id: "3-1",
        name: "Quadros e Painéis",
        slug: "quadros",
        description: "Arte para paredes com diversos estilos",
        image: "/images/quadros-paineis.png",
        parentId: "3",
      },
      {
        id: "3-2",
        name: "Almofadas Decorativas",
        slug: "almofadas",
        description: "Conforto e estilo para sofás e camas",
        image: "/images/almofadas.png",
        parentId: "3",
      },
      {
        id: "3-3",
        name: "Vasos e Plantas",
        slug: "vasos",
        description: "Verde e vida para seus ambientes",
        image: "/images/vasos-plantas.png",
        parentId: "3",
      },
      {
        id: "3-4",
        name: "Espelhos Decorativos",
        slug: "espelhos",
        description: "Amplitude e elegância para qualquer espaço",
        image: "/images/espelhos.png",
        parentId: "3",
      },
    ],
  },
]

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Papel de Parede Floral Vintage",
    description: "Papel de parede vinílico com padrão floral vintage, perfeito para salas e quartos românticos.",
    price: 89.9,
    originalPrice: 119.9,
    category: "papel-de-parede",
    subcategory: "Vinílico",
    brand: "WallArt Premium",
    images: ["/images/papel-floral-vintage.png", "/images/papel-floral-detail.png"],
    stock: 150,
    pattern: "Floral",
    texture: "Lisa",
    rollWidth: 53,
    rollLength: 10,
    coverage: 5.3,
    washable: true,
    removable: true,
    color: "Rosa Antigo",
    style: "Vintage",
    room: ["sala", "quarto"],
    rating: 4.8,
    reviews: 127,
    featured: true,
    tags: ["floral", "vintage", "romântico", "lavável"],
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Cortina Blackout Elegance",
    description: "Cortina blackout em tecido premium, bloqueio total de luz com elegância moderna.",
    price: 299.9,
    originalPrice: 399.9,
    category: "cortinas",
    subcategory: "Blackout",
    brand: "Cortinas & Cia",
    images: ["/images/cortina-blackout-elegance.png", "/images/cortina-blackout-detail.png"],
    stock: 45,
    fabricType: "Poliéster Premium",
    opacity: "blackout",
    width: 200,
    height: 250,
    installationType: "trilho",
    color: "Cinza Chumbo",
    style: "Moderno",
    room: ["quarto", "home-theater"],
    rating: 4.9,
    reviews: 89,
    featured: true,
    tags: ["blackout", "moderno", "premium", "sob-medida"],
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "3",
    name: "Papel de Parede Geométrico 3D",
    description: "Papel de parede com efeito 3D e padrões geométricos modernos, ideal para salas contemporâneas.",
    price: 159.9,
    category: "papel-de-parede",
    subcategory: "3D",
    brand: "Modern Wall",
    images: ["/images/papel-geometrico-3d.png", "/images/papel-3d-texture.png"],
    stock: 80,
    pattern: "Geométrico",
    texture: "3D Relevo",
    rollWidth: 53,
    rollLength: 10,
    coverage: 5.3,
    washable: true,
    removable: false,
    color: "Branco e Cinza",
    style: "Moderno",
    room: ["sala", "escritório"],
    rating: 4.7,
    reviews: 203,
    featured: true,
    tags: ["3d", "geométrico", "moderno", "relevo"],
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "4",
    name: "Cortina Translúcida Zen",
    description: "Cortina translúcida em linho natural, filtragem suave da luz com toque zen.",
    price: 189.9,
    category: "cortinas",
    subcategory: "Translúcidas",
    brand: "Zen Home",
    images: ["/images/cortina-zen.png", "/images/cortina-linho.png"],
    stock: 60,
    fabricType: "Linho Natural",
    opacity: "translucido",
    width: 180,
    height: 220,
    installationType: "varão",
    color: "Bege Natural",
    style: "Zen",
    room: ["sala", "quarto"],
    rating: 4.6,
    reviews: 156,
    featured: false,
    tags: ["linho", "natural", "zen", "translúcido"],
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "5",
    name: "Quadro Abstrato Dourado",
    description: "Quadro decorativo abstrato com detalhes dourados, moldura premium inclusa.",
    price: 249.9,
    category: "decoracao",
    subcategory: "Quadros",
    brand: "Arte & Estilo",
    images: ["/images/quadro-abstrato-dourado.png", "/images/quadro-moldura.png"],
    stock: 25,
    dimensions: { width: 80, height: 60, depth: 3 },
    weight: 2.5,
    material: "Tela Canvas Premium",
    color: "Dourado e Preto",
    style: "Abstrato",
    room: ["sala", "escritório", "quarto"],
    rating: 4.8,
    reviews: 78,
    featured: true,
    tags: ["abstrato", "dourado", "premium", "moldura"],
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "6",
    name: "Papel de Parede Infantil Unicórnios",
    description: "Papel de parede TNT com unicórnios coloridos, perfeito para quartos infantis femininos.",
    price: 69.9,
    category: "papel-de-parede",
    subcategory: "Infantil",
    brand: "Kids Wall",
    images: ["/images/papel-unicornios.png", "/images/papel-infantil-detail.png"],
    stock: 120,
    pattern: "Unicórnios",
    texture: "Lisa",
    rollWidth: 53,
    rollLength: 10,
    coverage: 5.3,
    washable: true,
    removable: true,
    color: "Rosa e Lilás",
    style: "Infantil",
    room: ["quarto-infantil"],
    rating: 4.9,
    reviews: 245,
    featured: false,
    tags: ["infantil", "unicórnio", "colorido", "meninas"],
    createdAt: new Date("2024-01-25"),
  },
]

export const mockCustomers: Customer[] = [
  {
    id: "1",
    name: "Maria Silva",
    email: "maria@email.com",
    role: "customer",
    cpf: "123.456.789-00",
    phone: "(11) 99999-9999",
    birthDate: new Date("1985-05-15"),
    createdAt: new Date("2023-01-15"),
    addresses: [],
    orders: [],
    wishlist: ["1", "2"],
    loyaltyPoints: 1250,
    totalSpent: 5670.8,
    preferredStyle: "Moderno",
    preferredRooms: ["sala", "quarto"],
  },
  {
    id: "2",
    name: "João Santos",
    email: "joao@email.com",
    role: "customer",
    cpf: "987.654.321-00",
    phone: "(11) 88888-8888",
    birthDate: new Date("1990-08-22"),
    createdAt: new Date("2023-03-10"),
    addresses: [],
    orders: [],
    wishlist: ["3", "4"],
    loyaltyPoints: 890,
    totalSpent: 3240.5,
    preferredStyle: "Clássico",
    preferredRooms: ["sala", "escritório"],
  },
]

export const mockEmployees: Employee[] = [
  {
    id: "1",
    name: "Ana Costa",
    email: "ana@decoracao.com",
    role: "Consultora de Decoração",
    department: "Vendas",
    salary: 8500,
    hireDate: new Date("2022-01-15"),
    status: "active",
    permissions: ["sales", "customers", "consultation"],
    specialties: ["consultoria", "papel-de-parede", "cortinas"],
  },
  {
    id: "2",
    name: "Carlos Oliveira",
    email: "carlos@decoracao.com",
    role: "Técnico de Medição",
    department: "Serviços",
    salary: 4500,
    hireDate: new Date("2023-06-01"),
    status: "active",
    permissions: ["measurement", "installation"],
    specialties: ["medição", "instalação"],
  },
  {
    id: "3",
    name: "Fernanda Lima",
    email: "fernanda@decoracao.com",
    role: "Instaladora de Papel de Parede",
    department: "Serviços",
    salary: 5200,
    hireDate: new Date("2022-08-10"),
    status: "active",
    permissions: ["installation"],
    specialties: ["instalação", "papel-de-parede"],
  },
]

export const mockSuppliers: Supplier[] = [
  {
    id: "1",
    name: "WallPaper Brasil Ltda",
    cnpj: "12.345.678/0001-90",
    email: "contato@wallpaperBrasil.com",
    phone: "(11) 3333-3333",
    address: {
      id: "1",
      street: "Rua das Indústrias",
      number: "1000",
      neighborhood: "Industrial",
      city: "São Paulo",
      state: "SP",
      zipCode: "01234-567",
      country: "Brasil",
      isDefault: true,
    },
    products: ["1", "3", "6"],
    paymentTerms: "30 dias",
    status: "active",
    specialty: "papel-de-parede",
    leadTime: 15,
    minimumOrder: 1000,
  },
  {
    id: "2",
    name: "Cortinas Premium S.A.",
    cnpj: "98.765.432/0001-10",
    email: "vendas@cortinaspremium.com",
    phone: "(11) 4444-4444",
    address: {
      id: "2",
      street: "Av. Têxtil",
      number: "500",
      neighborhood: "Vila Madalena",
      city: "São Paulo",
      state: "SP",
      zipCode: "05432-100",
      country: "Brasil",
      isDefault: true,
    },
    products: ["2", "4"],
    paymentTerms: "45 dias",
    status: "active",
    specialty: "cortinas",
    leadTime: 20,
    minimumOrder: 500,
  },
]

export const mockMeasurements: MeasurementService[] = [
  {
    id: "1",
    customerId: "1",
    address: {
      id: "1",
      street: "Rua das Flores",
      number: "123",
      neighborhood: "Jardins",
      city: "São Paulo",
      state: "SP",
      zipCode: "01234-567",
      country: "Brasil",
      isDefault: true,
    },
    scheduledDate: new Date("2024-03-15T14:00:00"),
    status: "scheduled",
    rooms: [
      {
        name: "Sala de Estar",
        measurements: {
          walls: [
            { width: 400, height: 280 },
            { width: 350, height: 280 },
          ],
          windows: [{ width: 150, height: 120 }],
        },
      },
    ],
    notes: "Cliente quer papel de parede na parede principal",
    technician: "Carlos Oliveira",
  },
]

export const mockInstallations: InstallationService[] = [
  {
    id: "1",
    orderId: "ORD-001",
    customerId: "1",
    address: {
      id: "1",
      street: "Rua das Flores",
      number: "123",
      neighborhood: "Jardins",
      city: "São Paulo",
      state: "SP",
      zipCode: "01234-567",
      country: "Brasil",
      isDefault: true,
    },
    scheduledDate: new Date("2024-03-20T09:00:00"),
    status: "scheduled",
    serviceType: "papel-de-parede",
    technician: "Fernanda Lima",
    estimatedDuration: 6,
    notes: "Instalação de papel de parede na sala de estar",
  },
]
